name: Compile sketches

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fqbn:
          - arduino:avr:uno
          - arduino:avr:nano
          - arduino:avr:mega
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.fqbn }}
          sketch-paths: |
            - joystick_test
          cli-compile-flags: |
            - --warnings
            - all
